id: IC41D591C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T11:07:05+00:00'
last_modified: '2022-06-07T18:44:38.948989+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W21923
  title: གེ་སར་སྒྲུང་གི་ཚིག་འགྲེལ་གསལ་སྒྲོན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    E442:
      image_group_id: I5706
      title: ''
      total_pages: 326
      order: 1
      base_file: E442.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
