id: P003266
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W21923
  title: གེ་སར་སྒྲུང་གི་ཚིག་འགྲེལ་གསལ་སྒྲོན།
  author: ''
  volumes:
    c2b4b276cc944abc88559dc2898b1625:
      image_group_id: I5706
      title: ''
      volume_number: 1
      total_pages: 326
      base_file: v001.txt
